// Generated by LiveScript 1.3.1
var start, isBlink, isLight, isRun, isShow, isWarned, handler, latency, stopBy, delay, audioRemind, sunWrap, sun, sunRays, sunDuration, roosterContext, roosterTimers, rooster, roosterShown, newAudio, soundToggle, show, adjust, toggle, reset, blink, count, run, resize, updateSunPosition, updateSunAppearance, startRoosterCountdown, triggerRoosterCrow, stopRoosterCrow, hideRooster;
start = null;
isBlink = false;
isLight = true;
isRun = false;
isShow = true;
isWarned = false;
handler = null;
latency = 0;
stopBy = null;
delay = 60000;
audioRemind = null;
sunWrap = null;
sun = null;
sunRays = null;
sunDuration = 0;
roosterContext = null;
roosterTimers = [];
rooster = null;
roosterShown = false;
newAudio = function(file){
  var x$, node;
  x$ = node = new Audio();
  x$.src = file;
  x$.loop = false;
  x$.load();
  document.body.appendChild(node);
  return node;
};
soundToggle = function(des, state){
  var x$;
  if (state) {
    return des.play();
  } else {
    x$ = des;
    x$.currentTime = 0;
    x$.pause();
    return x$;
  }
};
show = function(){
  isShow = !isShow;
  return $('.fbtn').css('opacity', isShow ? '1.0' : '0.1');
};
adjust = function(it, v){
  if (isBlink) {
    return;
  }
  delay = delay + it * 1000;
  if (it === 0) {
    delay = v * 1000;
  }
  if (delay <= 0) {
    delay = 0;
  }
  $('#timer').text(delay);
  if (!isRun) {
    sunDuration = delay;
    updateSunPosition(delay);
  }
  return resize();
};
toggle = function(){
  isRun = !isRun;
  $('#toggle').text(isRun ? "STOP" : "RUN");
  if (!isRun && handler) {
    stopBy = new Date();
    clearInterval(handler);
    handler = null;
    stopRoosterCrow();
    hideRooster();
    soundToggle(audioRemind, false);
  }
  if (stopBy) {
    latency = latency + new Date().getTime() - stopBy.getTime();
  }
  if (isRun) {
    return run();
  }
};
reset = function(){
  if (delay === 0) {
    delay = 1000;
  }
  soundToggle(audioRemind, false);
  stopRoosterCrow();
  hideRooster();
  stopBy = 0;
  isWarned = false;
  isBlink = false;
  latency = 0;
  start = null;
  isRun = true;
  toggle();
  if (handler) {
    clearInterval(handler);
  }
  handler = null;
  $('#timer').text(delay);
  $('#timer').css('color', '#fff');
  sunDuration = delay;
  updateSunPosition(delay);
  return resize();
};
blink = function(){
  isBlink = true;
  isLight = !isLight;
  return $('#timer').css('color', isLight ? '#fff' : '#f00');
};
count = function(){
  var tm, diff;
  tm = $('#timer');
  diff = start.getTime() - new Date().getTime() + delay + latency;
  updateSunPosition(Math.max(0, diff));
  if (diff > 60000) {
    isWarned = false;
  }
  if (diff < 60000 && !isWarned) {
    isWarned = true;
    soundToggle(audioRemind, true);
  }
  if (diff < 55000) {
    soundToggle(audioRemind, false);
  }
  if (diff <= 3000 && diff > 0 && !roosterShown) {
    startRoosterCountdown();
  }
  if (diff < 0 && !isBlink) {
    updateSunPosition(0);
    isBlink = true;
    diff = 0;
    clearInterval(handler);
    handler = setInterval(function(){
      return blink();
    }, 500);
  }
  tm.text(diff + "");
  return resize();
};
run = function(){
  if (start === null) {
    start = new Date();
    latency = 0;
    isBlink = false;
    sunDuration = delay;
    updateSunPosition(delay);
  }
  if (handler) {
    clearInterval(handler);
  }
  if (isBlink) {
    return handler = setInterval(function(){
      return blink();
    }, 500);
  } else {
    return handler = setInterval(function(){
      return count();
    }, 100);
  }
};
resize = function(){
  var tm, w, h, len;
  tm = $('#timer');
  w = tm.width();
  h = $(window).height();
  len = tm.text().length;
  len >= 3 || (len = 3);
  tm.css('font-size', 1.5 * w / len + "px");
  return tm.css('line-height', h + "px");
};
updateSunPosition = function(remaining){
  var progress, target;
  if (!sunWrap || !sun || sunDuration <= 0) {
    return;
  }
  progress = 1 - remaining / sunDuration;
  if (progress < 0) {
    progress = 0;
  }
  if (progress > 1) {
    progress = 1;
  }
  target = -25 + progress * 95;
  sunWrap.style.bottom = target + "vh";
  return updateSunAppearance(progress);
};
updateSunAppearance = function(progress){
  var scale, rayScale, glowStrength;
  if (!sun || !sunRays) {
    return;
  }
  scale = 1 + progress * 0.6;
  rayScale = 0.9 + progress * 0.8;
  glowStrength = 40 + progress * 60;
  sun.style.transform = "scale(" + scale + ")";
  sun.style.boxShadow = "0 0 " + glowStrength + "px rgba(255, 188, 38, 0.8), 0 0 " + glowStrength * 1.6 + "px rgba(255, 188, 38, 0.4)";
  sunRays.style.opacity = 0.15 + progress * 0.7 + "";
  return sunRays.style.transform = "scale(" + rayScale + ")";
};
startRoosterCountdown = function(){
  if (roosterShown) {
    return;
  }
  roosterShown = true;
  if (rooster) {
    rooster.classList.add('show');
  }
  return triggerRoosterCrow();
};
triggerRoosterCrow = function(){
  var ctx, base, i$;
  stopRoosterCrow();
  ctx = roosterContext || (roosterContext = new (window.AudioContext || window.webkitAudioContext)());
  ctx.resume();
  base = ctx.currentTime + 0.05;
  for (i$ = 0; i$ < 3; ++i$) {
    (fn$.call(this, i$));
  }
  function fn$(idx){
    var startTime, osc, gain;
    startTime = base + idx * 1.1;
    osc = ctx.createOscillator();
    gain = ctx.createGain();
    osc.type = 'square';
    osc.frequency.setValueAtTime(520, startTime);
    osc.frequency.exponentialRampToValueAtTime(420, startTime + 0.18);
    osc.frequency.exponentialRampToValueAtTime(540, startTime + 0.35);
    osc.frequency.exponentialRampToValueAtTime(360, startTime + 0.55);
    gain.gain.setValueAtTime(0.0001, startTime);
    gain.gain.exponentialRampToValueAtTime(0.45, startTime + 0.05);
    gain.gain.exponentialRampToValueAtTime(0.0001, startTime + 0.75);
    osc.connect(gain);
    gain.connect(ctx.destination);
    osc.start(startTime);
    osc.stop(startTime + 0.9);
    return roosterTimers.push(setTimeout(function(){
      osc.disconnect();
      return gain.disconnect();
    }, (startTime - ctx.currentTime + 1) * 1000));
  }
};
stopRoosterCrow = function(){
  var i$;
  for (i$ = 0; i$ < roosterTimers.length; ++i$) {
    clearTimeout(roosterTimers[i$]);
  }
  return roosterTimers = [];
};
hideRooster = function(){
  roosterShown = false;
  stopRoosterCrow();
  if (rooster) {
    return rooster.classList.remove('show');
  }
};
window.onload = function(){
  $('#timer').text(delay);
  sunWrap = document.getElementById('sun-wrap');
  sun = document.getElementById('sun');
  sunRays = document.getElementById('sun-rays');
  rooster = document.getElementById('rooster');
  sunDuration = delay;
  updateSunPosition(delay);
  resize();
  return audioRemind = newAudio('audio/smb_warning.mp3');
};
window.onresize = function(){
  return resize();
};